### ISSUE TITLE
[Feature] Would be nice to be able to delete locations with the map

### ISSUE THREAD

**Issue by Arttumiro** [xenDE/pwnagotchi-plugin-webgpsmap#14]
Like deleting the paw-gps.json or geo.json files without having to go into /root/handshakes every time through the website somehow, if this is not possible its all fine but it would be nice for inaccurate data and for cleaning up the map

**Comment by xenDE** [comment]
this should be an other plugin.

gpsmap shows only handshakes with geo/gps data
