### ISSUE TITLE
need to filter bad positions like (lat:0, long:0)

### ISSUE THREAD

**Issue by xenDE** [xenDE/pwnagotchi-plugin-webgpsmap#3]
filter/ignore not valid positions

example of bad gps data:
{"Updated": "0001-01-01T00:00:00Z", "Latitude": 0, "Longitude": 0, "FixQuality": "", "NumSatellites": 0, "HDOP": 0, "Altitude": 0, "Separation": 0}

**Comment by dadav** [comment]
fixed
