### ISSUE TITLE
error on files without SSID/"_"

### ISSUE THREAD

**Issue by xenDE** [xenDE/pwnagotchi-plugin-webgpsmap#4]
some files breaks the parsing:

c8bcc8fe6353.geo.json
c8bcc8fe6353.net-pos.json
c8bcc8fe6353.pcap

  File "/usr/local/pwnagotchi/plugins/webgpsmap.py", line 177, in get_html
    gps_data = get_gps_data()
  File "/usr/local/pwnagotchi/plugins/webgpsmap.py", line 154, in get_gps_data
    ssid, mac = os.path.basename(pos_file).split('.', 2)[0].split('_', 1)
ValueError: not enough values to unpack (expected 2, got 1)

^^line numbers are not correct!

**Comment by xenDE** [comment]
added "unknown_" in front.

solution looks not good for me ;(

**Comment by dadav** [comment]
Sometime you just don't know the ssid, because no beacons were received yet. We cant fix that :(

**Comment by dadav** [comment]
fixed

**Comment by xenDE** [comment]
> Sometimes you just don't know the ssid, because no beacons were received yet. We cant fix that :(

yep, the problem was the filename parser, not the created filenames.
